const fs = require('fs');
const path = 'ocak_2026_data.json';
const obj = JSON.parse(fs.readFileSync(path, 'utf8'));
const data = obj.records || obj || [];
const counts = {};
data.forEach(r => { const a = (r.AMBAR || '').toString().trim(); counts[a] = (counts[a]||0) + 1 });
const sorted = Object.entries(counts).sort((a,b) => b[1]-a[1]);
console.log('AMBAR counts:\n' + sorted.map(x=>x.join(': ')).join('\n'));
const recs = data.filter(r => String(r.AMBAR).trim() === '2');
console.log('\n\nAMBAR==="2" sample count=' + recs.length + '\n');
console.log(JSON.stringify(recs.slice(0,5), null, 2));
