const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getData: (query) => ipcRenderer.invoke('get-data', query),
  getAllData: () => ipcRenderer.invoke('get-all-data'),
  getDashboardStats: (ambarFilter) => ipcRenderer.invoke('get-dashboard-stats', ambarFilter),
  getAmbarList: () => ipcRenderer.invoke('get-ambar-list'),
  getFactoryComparison: () => ipcRenderer.invoke('get-factory-comparison'),
  testConnection: () => ipcRenderer.invoke('test-connection'),
  // Window controls
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  windowIsMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  restartForUpdate: () => ipcRenderer.invoke('restart-for-update'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (_event, info) => callback(info)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', (_event, info) => callback(info)),
  onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (_event, progress) => callback(progress)),
  onUpdateNotAvailable: (callback) => ipcRenderer.on('update-not-available', (_event, info) => callback(info)),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (_event, msg) => callback(msg)),
  // Dosya Yönetimi
  dosyaListele: (siparisNo) => ipcRenderer.invoke('dosya-listele', siparisNo),
  dosyaSayilari: (siparisNolar) => ipcRenderer.invoke('dosya-sayilari', siparisNolar),
  dosyaYukle: (params) => ipcRenderer.invoke('dosya-yukle', params),
  dosyaSil: (id) => ipcRenderer.invoke('dosya-sil', id),
  dosyaIndir: (params) => ipcRenderer.invoke('dosya-indir', params),
  dosyaGoruntule: (id) => ipcRenderer.invoke('dosya-goruntule', id),
  dosyaGoruntuleUrl: (id) => ipcRenderer.invoke('dosya-goruntule-url', id),
  // İhale Yönetimi
  ihaleList: (params) => ipcRenderer.invoke('ihale-list', params),
  ihaleGet: (siraNo) => ipcRenderer.invoke('ihale-get', siraNo),
  ihaleCreate: (dto) => ipcRenderer.invoke('ihale-create', dto),
  ihaleUpdate: (siraNo, dto) => ipcRenderer.invoke('ihale-update', { siraNo, dto }),
  ihaleDelete: (siraNo) => ipcRenderer.invoke('ihale-delete', siraNo),
  ihaleLokasyonlar: () => ipcRenderer.invoke('ihale-lokasyonlar'),
  ihaleRaporOzet: (params) => ipcRenderer.invoke('ihale-rapor-ozet', params),
  ihaleRaporLokasyon: (params) => ipcRenderer.invoke('ihale-rapor-lokasyon', params),
  ihaleRaporTedarikci: (params) => ipcRenderer.invoke('ihale-rapor-tedarikci', params),
  ihaleRaporMasrafMerkezi: (params) => ipcRenderer.invoke('ihale-rapor-masraf-merkezi', params),
  ihaleRaporRekabet: (params) => ipcRenderer.invoke('ihale-rapor-rekabet', params),
  ihaleRaporTrend: (params) => ipcRenderer.invoke('ihale-rapor-trend', params),
  ihaleRaporTasarruf: (params) => ipcRenderer.invoke('ihale-rapor-tasarruf', params),
  // Tedarikçi Kategori
  tedarikciKategoriList: (params) => ipcRenderer.invoke('tedarikci-kategori-list', params),
  tedarikciKategoriGet: (id) => ipcRenderer.invoke('tedarikci-kategori-get', id),
  tedarikciKategoriCreate: (dto) => ipcRenderer.invoke('tedarikci-kategori-create', dto),
  tedarikciKategoriUpdate: (id, dto) => ipcRenderer.invoke('tedarikci-kategori-update', { id, dto }),
  tedarikciKategoriDelete: (id) => ipcRenderer.invoke('tedarikci-kategori-delete', id),
  tedarikciKategoriRaporIstatistik: () => ipcRenderer.invoke('tedarikci-kategori-rapor-istatistik'),
  tedarikciKategoriRaporKategoriOzet: (params) => ipcRenderer.invoke('tedarikci-kategori-rapor-kategori-ozet', params),
  tedarikciKategoriRaporTipDagilimi: () => ipcRenderer.invoke('tedarikci-kategori-rapor-tip-dagilimi'),
  tedarikciKategoriRaporTedarikciProfil: (params) => ipcRenderer.invoke('tedarikci-kategori-rapor-tedarikci-profil', params),
  tedarikciKategoriRaporEksikBilgi: () => ipcRenderer.invoke('tedarikci-kategori-rapor-eksik-bilgi'),
  tedarikciKategoriRaporCokluKategori: () => ipcRenderer.invoke('tedarikci-kategori-rapor-coklu-kategori'),
  tedarikciKategoriRaporKategoriKarsilastirma: (params) => ipcRenderer.invoke('tedarikci-kategori-rapor-kategori-karsilastirma', params),
  tedarikciKategoriRaporKategoriListesi: () => ipcRenderer.invoke('tedarikci-kategori-rapor-kategori-listesi'),
});
